"""migration

Revision ID: 2075c9f8e9da
Revises: 22c2a88628a0
Create Date: 2019-06-02 17:06:05.300610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2075c9f8e9da'
down_revision = '22c2a88628a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_comments_username'), 'comments', ['username'], unique=False)
    op.add_column('posts', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_posts_username'), 'posts', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_username'), table_name='posts')
    op.drop_column('posts', 'username')
    op.drop_index(op.f('ix_comments_username'), table_name='comments')
    op.drop_column('comments', 'username')
    # ### end Alembic commands ###
