"""migration

Revision ID: 22c2a88628a0
Revises: 453f388dd816
Create Date: 2019-06-02 17:00:57.698871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c2a88628a0'
down_revision = '453f388dd816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('posted', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'posted')
    # ### end Alembic commands ###
