"""migration

Revision ID: 65aadc851992
Revises: 3a7d7335a9a5
Create Date: 2019-06-02 17:53:50.240689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65aadc851992'
down_revision = '3a7d7335a9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'title')
    # ### end Alembic commands ###
